### ISSUE TITLE
Compile error on MSVC on UTF-8 charset

### ISSUE THREAD

**Issue by acane77** [openvinotoolkit/openvino.genai#1094]
MSVC generates compile error (newline in string literal) on the unrecongnized question mark character in this line (https://github.com/openvinotoolkit/openvino.genai/blob/master/src/cpp/src/text_callback_streamer.cpp#L26) on UTF-8 charset (with `/utf-8` compile flag).

```
    if (text.size() >= 3 && text.compare(text.size() - 3, 3, "�") == 0) {
```

As this condition only compares 3-byte UTF-8 sequence, it's better to use code sequence encoded in UTF-8 instead of directly use the character itself.

```
    if (text.size() >= 3 && text.compare(text.size() - 3, 3, "\xef\xbf\xbd") == 0) {
```

**Comment by Wovchena** [comment]
Fix: https://github.com/openvinotoolkit/openvino.genai/pull/1095
