### ISSUE TITLE
Support for Initial Prompt and Hotwords in WhisperPipeline (similar to faster-whisper)

### ISSUE THREAD

**Issue by HighBridgeDragon** [openvinotoolkit/openvino.genai#1150]
Hello OpenVINO team,

I'm currently using the WhisperPipeline in openvino.genai and would like to request a feature similar to that of [faster-whisper](https://github.com/SYSTRAN/faster-whisper/) (CTranslate2), where users can provide an [initial_prompt](https://github.com/SYSTRAN/faster-whisper/blob/203dddb047fd2c3ed2a520fe1416467a527e0f37/faster_whisper/transcribe.py#L732) or specify [hotwords](https://github.com/SYSTRAN/faster-whisper/blob/203dddb047fd2c3ed2a520fe1416467a527e0f37/faster_whisper/transcribe.py#L768) to influence the transcription process.

This feature would be particularly useful in cases where we want to improve transcription accuracy for specific terms or in domain-specific contexts.

Feature Request:

- Add support for initial_prompt in the WhisperPipeline.
- Add support for hotwords or custom vocabulary injection, allowing users to specify words/phrases that are prioritized during transcription.

Is there any existing workaround or plan to incorporate these features in openvino.genai?

Thank you for considering this feature request!

**Comment by as-suvorov** [comment]
Hello, thanks for a request! I'll review it.

**Comment by HighBridgeDragon** [comment]
@as-suvorov 

Thank you so much for resolving this issue! Your effort is greatly appreciated.

I’m looking forward to the release of the prebuilt binary that includes your changes.

Additionally, I’m hopeful for the resolution of issue #1164  as well.

**Comment by as-suvorov** [comment]
@HighBridgeDragon 

You could already try this changes using nightly package, installation instructions: https://docs.openvino.ai/2024/get-started/install-openvino.html?PACKAGE=OPENVINO_GENAI&VERSION=NIGHTLY&OP_SYSTEM=LINUX&DISTRIBUTION=PIP
Your feedback will be highly appreciated.

I will give you an update when I get more news regarding Beam Search for the Whisper pipeline.
Thank you.
