### ISSUE TITLE
Issue with Token Latency Reporting for Second Token in OpenVINO GenAI LLM Models

### ISSUE THREAD

**Issue by manojrashinkar** [openvinotoolkit/openvino.genai#1277]
There has been a change in the OpenVINO GenAI Git repository. Recently, when I try to execute LLM models, I am getting a value for the first token latency, but the second token latency is coming up as N/A. Is there any fix for this?

STEPS: 
- Create a Conda environment with Python 3.10.11:
  
  conda create -n openvino_env python=3.10.11
  conda activate openvino_env

- Clone the `openvino.genai` repository:

  git clone https://github.com/openvinotoolkit/openvino.genai.git
  cd openvino.genai

PATH : https://github.com/openvinotoolkit/openvino.genai/tree/master/tools/llm_bench

- Install dependencies from the `requirements.txt` file:

  pip install -r tools/llm_bench/requirements.txt

- Download or place the model (e.g., `llama-2-7b-chat`) in the `models/` directory.

- Prepare the prompt file (e.g., `llama-2-7b-chat_l.jsonl`) and place it in the `prompts/` directory.

- Run the benchmark with the following command:

  python benchmark.py -m <model> -d <device> -r <report_csv> -f <framework> -p <prompt_text> -n <num_iters>
=

- Example command:

  python benchmark.py -m models/llama-2-7b-chat/ -pf prompts/llama-2-7b-chat_l.jsonl -n 2 -d GPU -r benchmark_results.csv -f openvino

- After running the benchmark , second token latency is coming up as N/A. Is there any fix for this

**Comment by Wan-Intel** [comment]
I've created a virtual environment with Python 3.10.12, clone the openvino.genai repository, and ran the following command:
`python benchmark.py -m ~/waifook_temp/openvino_notebooks/notebooks/llm-chatbot/llama-2-chat-7b/FP16 -p "how are you" -n 2 -d CPU`

I'm able to obtain second token latency. The result is shown as follows:
<img width="960" alt="result" src="https://github.com/user-attachments/assets/d54bec57-0960-41e6-8e60-d5ce50b42fe2">

May I know which operating system are you using on your machine? Do you encounter issue when using prompt text instead of prompt file? Could you please share the prompt file with us to replicate the issue from our end?

**Comment by manojrashinkar** [comment]
Prompt-file : https://github.com/openvinotoolkit/openvino.genai/blob/master/tools/llm_bench/prompts/llama-2-7b-chat_l.jsonl
Sorry i am running it on INTEL GPU  : python benchmark.py -m models/llama-2-7b-chat/ -pf prompts/llama-2-7b-chat_l.jsonl -n 2 -d GPU -r benchmark_results.csv -f openvino

**Comment by eaidova** [comment]
@manojrashinkar could you please provide info about transformers version that you use and result logs. Empty second tokens latency usually means that model finished generation after first inference and there is no any data to calculate second token latency. Possibily changing input [prompt may help with resolving this issue. The second possible reason that you use some of unsupported transformers version where hooks for performance measurements are not implemented. In this case please try to update / downgrade transformers. Also usage openvino genai (--genai) flag may help to overcome issue as it has own pipeline implementation that does not depends on transformers version

**Comment by manojrashinkar** [comment]
I've tried using transformers 4.46.0 and also 4.43.0, but I encountered some issues. Both versions were tested, but neither resolved the problem

**Comment by Wan-Intel** [comment]
I've run python benchmark.py -m models/llama-2-7b-chat/ -pf prompts/llama-2-7b-chat_l.jsonl -n 2 -d GPU

Here is the result of second latency:
<img width="960" alt="gpu ok json" src="https://github.com/user-attachments/assets/bea0180a-e8b6-4ec8-830f-dadaba63e3b9">

Referring to [eaidova](https://github.com/eaidova) comment, could you please try to change the input prompt and see if the issue can be resolved?

**Comment by Wan-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
