### ISSUE TITLE
winrt使用openvino.genai

### ISSUE THREAD

**Issue by qihui-liu** [openvinotoolkit/openvino.genai#1281]
May I ask how to call the relevant content of openvino.genai in the case of Winrt? Do you have any understanding? Currently, I am experiencing a failure while initializing LLMPipeline. Filesystem:: exists access failed But the path is correct
I am using the UWP&C++approach

**Comment by qihui-liu** [comment]
New issues.
UWP has path restrictions, so it cannot be determined. Therefore, I placed the model in the root directory, but the following problem occurred again
![image](https://github.com/user-attachments/assets/54e80f2d-67ff-4809-9646-ba9e5d8bd79d)

**Comment by Wan-Intel** [comment]
Universal Windows Platform isn't validated by OpenVINO™ GenAI. To build OpenVINO™ GenAI application in C++, please refer to [How to Build OpenVINO™ GenAI APP in C++](https://medium.com/openvino-toolkit/how-to-build-openvino-genai-app-in-c-32dcbe42fa67)

**Comment by Wan-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
