### ISSUE TITLE
[Infra] Use dependabot to update Python dependencies

### ISSUE THREAD

**Issue by ilya-lavrenov** [openvinotoolkit/openvino.genai#177]
Currently, dependencies in requirements files are not pinned and with new dependencies versions we have broken pipelines like on 2023.3 now.

Let's pin dependencies and use dependabot to track new versions and send updates as PRs. Such PRs can be tested on compatibility with our CI.

**Comment by Wovchena** [comment]
@peterchen-intel, do you have objections from llm_bench https://github.com/openvinotoolkit/openvino.genai/blob/master/llm_bench/python/requirements.txt point of view?

**Comment by Wovchena** [comment]
@eaidova has objections about llm_bench. I'm going to do that for the rest apps: image_generation.

**Comment by ilya-lavrenov** [comment]
@eaidova could you please share some points why pinning does not work for llm_bench ?

**Comment by eaidova** [comment]
> @eaidova could you please share some points why pinning does not work for llm_bench ?

it does not work until model configurations will not moved to optimum, now it maybe used as tool in existing env for collecting model wrappers and conversion API. Also it will requires update everytime when we support new model, while not all models maybe need for specific user who interested running only his specific model (and also not possible find working combination for all models in the same time(e.g. supporting mixtral requires transformers>=4.37, baichuan works only for transformers < 4.35)
