### ISSUE TITLE
Migrate to OpenVINO tokenizers repo

### ISSUE THREAD

**Issue by ilya-lavrenov** [openvinotoolkit/openvino.genai#228]
OpenVINO Tokenizers extension has a new home https://github.com/openvinotoolkit/openvino_tokenizers

Or maybe it's better to remove submodule and use release packages via cmake fetch content?

**Comment by Wovchena** [comment]
I consider three options:

1. PyPI for Python and C++ archive
2. PyPI for Python and extract library path for C++ from `py -c "import openvino_tokenizers; print(openvino_tokenizers._ext_path)"`
3. Submodule

The problem with first two options is that versions can mismatch.
1. Download C++ archives for OpenVINO and openvino_tokenizers, but pip may download different version. `convert_tokenizer` will generate tokenizer for different for different OpenVINO
2. The version at `openvino_tokenizers._ext_path` may be compiled for different OpenVINO.

The risk can be mitigated by providing python package inside of C++ archive just like OpenVINO does. Until openvino_tokenizers becomes a part of OpenVINO archive.

Submodule looks to be the simplest in terms of managing compatibility. The samples require compilation anyway.

**Comment by ilya-lavrenov** [comment]
> The version at openvino_tokenizers._ext_path may be compiled for different OpenVINO.

It will not work, because pip is built on CentOS (old C++ ABI) and such libs cannot be loaded on Ubuntu 18.04 and newer (new C++ ABI).

> PyPI for Python and C++ archive

If we use latest release versions, why would we have mismatch?

**Comment by Wovchena** [comment]
Sometimes nightly is required. As far as I know there's no nightly for `openvino_tokenizers` yet

**Comment by ilya-lavrenov** [comment]
As a first step I agree that migration to official OpenVINO Tokenizers repo can be done.
