### ISSUE TITLE
[Good First Issue]: causal_lm/cpp must read EOS token value from rt_info of openvino_tokenizer.xml

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino.genai#277]
### Context

End Of Sequence tokens are an essential part of LLM training and inference. You can find more details in [this comment](https://discuss.huggingface.co/t/how-does-gpt-decide-to-stop-generating-sentences-without-eos-token/41623/2).

Thanks to a [PR adding End Of Sequence tokens to Runtime Info](https://github.com/openvinotoolkit/openvino_tokenizers/pull/15/files#diff-7daa0a46d666790e3a6eb6bacb7b50bcf86ddc41d44d113cd9689374e36b6669R501) openvino_tokenizers now put EOS token value into rt_info section in OpenVINO Intermediate Representation format (`.xml` file to be specific) when converting a tokenizer to OpenVINO.

Since EOS has been enabled in OpenVINO, now it needs to be enabled in GenAI text_generation module.

### What needs to be done?

`beam_search_causal_lm.cpp` and `greedy_causal_lm.cpp` from https://github.com/openvinotoolkit/openvino.genai/tree/master/text_generation/causal_lm/cpp should read the EOS token instead of having a hardcoded value with comment  `// There's no way to extract special token values from the detokenizer for now`.

It’s required to extract the value using `ov::Model::get_rt_info()` and use it. Remove the comments about absence of way to extract that value.

### Example Pull Requests

-

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@pavel-esir

### Ticket

132861

**Comment by anzr299** [comment]
. take

**Comment by anzr299** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @anzr299, the ticket will be manually assigned to you shortly - the take feature hasn't been introduced to GenAI repo yet, but it will be today. :)

Thanks for taking a look at the issue!

**Comment by p-wysocki** [comment]
Hello @anzr299, are you still working on this? Is there anything we could help you with?

**Comment by anzr299** [comment]
Hi, I am still working on it, was busy the past few days.

**Comment by anzr299** [comment]
I've created a PR #315

**Comment by anzr299** [comment]
I have a small question, in `beam_search_casual_lm.cpp`, the following lines check for an empty token and not the hardcoded EOS token. Should I change this as well to check for the EOS token?
`if (next_tokens.empty()) {
            break;
        }`

**Comment by p-wysocki** [comment]
cc @pavel-esir

**Comment by pavel-esir** [comment]
> I have a small question, in `beam_search_casual_lm.cpp`, the following lines check for an empty token and not the hardcoded EOS token. Should I change this as well to check for the EOS token? `if (next_tokens.empty()) { break; }` (lines 60-62)

good question! No need to update beam_searcher, just initialize it with eos token you got from IR in the sample. Please look my comments in you PR.

**Comment by anzr299** [comment]
I am facing some difficulties in setting up my local environment to test the files.

**Comment by anzr299** [comment]
@ilya-lavrenov The issue asked to add a functionality to read EOS tokens only for beam_search_causal_lm and greedy_causal_lm but not for speculative_decoding_lm. I followed the requirement in my work but I thought it could be better if I added the functionality to speculative_decoding_lm too. Is that alright?

**Comment by ilya-lavrenov** [comment]
> I followed the requirement in my work but I thought it could be better if I added the functionality to speculative_decoding_lm too. Is that alright?

Yes, let's handle this sample as well.
The initial requirements were added before the speculative_decoding_lm sample is implemented.

**Comment by anzr299** [comment]
> > I followed the requirement in my work but I thought it could be better if I added the functionality to speculative_decoding_lm too. Is that alright?
> 
> Yes, let's handle this sample as well. The initial requirements were added before the speculative_decoding_lm sample is implemented.

Sure, I will create a new PR

**Comment by anzr299** [comment]
@ilya-lavrenov I've created a PR at #353
