### ISSUE TITLE
[Good First Issue]: Verify Phi-1_5 with GenAI text_generation

### ISSUE THREAD

**Issue by qxprakash** [openvinotoolkit/openvino.genai#302]
### Context

This task regards enabling tests for Phi-1_5. You can find more details under openvino_notebooks [LLM chatbot README.md](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/254-llm-chatbot).

Please ask general questions in the main issue at #259 

### What needs to be done?

Described in the main Discussion issue at: https://github.com/openvinotoolkit/openvino.genai/issues/259

### Example Pull Requests

Described in the main Discussion issue at: https://github.com/openvinotoolkit/openvino.genai/issues/259

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

Described in the main Discussion issue at: https://github.com/openvinotoolkit/openvino.genai/issues/259

**Comment by qxprakash** [comment]
.take

**Comment by tushar-thoriya** [comment]
.take

**Comment by mlukasze** [comment]
congratulations @qxprakash and thanks for contribution! 

another one? ;)

**Comment by qxprakash** [comment]
Thanks @mlukasze @pavel-esir for all your guidance , I want to contribute to more issues , Thanks !

**Comment by qxprakash** [comment]
@mlukasze @pavel-esir for every new model we add from now , we will have to add comparision tests for greedy decoding to match the results with HF library ? or is it only for specific models ?

**Comment by pavel-esir** [comment]
@qxprakash that's a good question. Think it's better to stick to this practice.  Comparison of a couple of sentences is a computationally lightweight action. The only thing is that workflow files get bigger with duplicated, i think of moving the comparison lines into a separate file and just call it.

So at the moment let's continue adding new tests in similar fashion as you did with phi_1.5

**Comment by qxprakash** [comment]
@pavel-esir I tried running few more models ,  `stabilityai/stablelm-2-zephyr-1_6b`  , `google/gemma-2b`  in both the cases I faced similar errors , 


 raise ValueError(
ValueError: The checkpoint you are trying to load has model type gemma but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

in the step **Download and convert the model and tokenizers**

where I ran `python3 ../../../llm_bench/python/convert.py --model_id google/gemma-2b --output_dir ./Gemma/ --precision FP16`
