### ISSUE TITLE
Falcon-40B convert successfully but output_dir has not been created

### ISSUE THREAD

**Issue by JunxiChhen** [openvinotoolkit/openvino.genai#355]
Convert cmd:
```
python3 convert.py         --model_id tiiuae/falcon-40b         --output_dir /root/.cache/huggingface/hub/tiiuae/falcon-40b-ov         --stateful --precision FP16
```
Benchmarking cmd:
```
numactl -C 0-55 -m 0 python benchmark.py     -m /root/.cache/huggingface/hub/falcon-40b-ov/pytorch/dldt/FP16  -p "It is done" -n 3     -bs 1     -d CPU --torch_compile_backend openvino     -ic 128 --num_beams 1 -lc bfloat16_config.json 2>&1 | tee -a ./logs/0.log
```
1. Model converting successfully to /root/.cache/huggingface/hub/tiiuae/falcon-40b-ov:
![image](https://github.com/openvinotoolkit/openvino.genai/assets/92417411/b9827dae-13fa-4394-8395-e5cb339b6e97)
2. Model cannot be found during benchmarking:
![image](https://github.com/openvinotoolkit/openvino.genai/assets/92417411/cb74f74a-4ae1-4a25-abbc-7c2cc1908515)
3. Dir /root/.cache/huggingface/hub/tiiuae/falcon-40b-ov does not exist.

**Comment by eaidova** [comment]
@JunxiChhen  I do not see in your logs that model successfully converted, is there possibility that this directory does not have write permissions?

**Comment by JunxiChhen** [comment]
We have write permission actually. We can successfully convert models in same directory including llama2, gpt-j, ... Could you have a try and check if there's same issue? Thanks. @eaidova

**Comment by eaidova** [comment]
@JunxiChhen Unfortunately, my working machine does not have enough RAM for conversion falcon-40b, so I can not check it, but if you can share more logs for conversion (better in text format instead of screenshot), it will be very helpful)

**Comment by JunxiChhen** [comment]
[benchmark_latency__bfloat16___04-23-24-06-25-42.log](https://github.com/openvinotoolkit/openvino.genai/files/15072747/benchmark_latency__bfloat16___04-23-24-06-25-42.log)
Here is the log file.

**Comment by eaidova** [comment]
@JunxiChhen possibly it is some logging issue, but on my side I can not see the same behaviour. On my end model conversion failed with 
`RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 8 but got size 128 for tensor number 1 in the list.`

I prepared fix for that https://github.com/huggingface/optimum-intel/pull/685

**Comment by eaidova** [comment]
@JunxiChhen could you please check falcon with the latest openvino.genai? the fix in optimum-intel was merged, commit is moved in llm_bench requirements.txt

**Comment by eaidova** [comment]
@JunxiChhen maybe setting of these variables may help avoiding reaching hf hub https://huggingface.co/docs/transformers/main/en/installation#offline-mode?

**Comment by JunxiChhen** [comment]
We downgraded the transformers version to 4.39.1 and passed. Thanks @eaidova
