### ISSUE TITLE
Convert failed using Salesforce/codegen25-7b-multi

### ISSUE THREAD

**Issue by JunxiChhen** [openvinotoolkit/openvino.genai#356]
Convert cmd:
```
python3 convert.py         --model_id Salesforce/codegen25-7b-multi         --output_dir /root/.cache/huggingface/hub/mpt-30b-chat-ov         --stateful --precision FP16
```
Convert failed:
![image](https://github.com/openvinotoolkit/openvino.genai/assets/92417411/77abf7b2-727d-4bf5-8be3-9bc5632ce065)

**Comment by eaidova** [comment]
@JunxiChhen this is not llm bench issue, but model itself. if you will use pytorch model, it returns the same error. There is an issue on huggingface hub about this problem and incompatibility model and transformers>4.34 https://huggingface.co/Salesforce/codegen25-7b-multi_P/discussions/10

I have prepared patch for fixing that, but models authors no longer maintain repo and do not merge it

https://huggingface.co/Salesforce/codegen25-7b-multi_P/discussions/12

**Comment by JunxiChhen** [comment]
Thanks @eaidova We will patch this file to our local model.
