### ISSUE TITLE
Convert failed of baichuan-inc/Baichuan2-13B-Chat

### ISSUE THREAD

**Issue by JunxiChhen** [openvinotoolkit/openvino.genai#357]
Convert cmd:
```
Convert cmd: python3 convert.py         --model_id baichuan-inc/Baichuan2-13B-Chat         --output_dir /root/.cache/huggingface/hub/baichuan2-13b-chat-ov         --stateful --precision FP16
```
![image](https://github.com/openvinotoolkit/openvino.genai/assets/92417411/57256ee5-cf7c-48a7-82c8-4b8fe978fd21)

BTW, Baichuan2-7B works well

**Comment by eaidova** [comment]
will be fixed in https://github.com/huggingface/optimum-intel/pull/676
