### ISSUE TITLE
[Improvement] Wrong output size of google/flan-t5-xl

### ISSUE THREAD

**Issue by JunxiChhen** [openvinotoolkit/openvino.genai#358]
Benchmark cmd:
```
numactl -C 0-55 -m 0 python benchmark.py     -m /root/.cache/huggingface/hub/flan-t5-xl-ov/pytorch/dldt/FP16     -p "It is done..."     -n 3     -bs 1
-d CPU --torch_compile_backend openvino     -ic 128 --num_beams 1 -lc bfloat16_config.json 2>&1 | tee -a ./logs/0.log
```

The -ic is 128 but got 129 in output log:
![image](https://github.com/openvinotoolkit/openvino.genai/assets/92417411/c2ece63a-3d52-4d3c-a516-a2aea766668c)

**Comment by JunxiChhen** [comment]
BTW, we also try different input/output cominations such as 1024/32 and 256/32, we also got the output size 33 (always output 1 more token than expected).
And we tried other models such as Llama2 also, the output tokens are generated as expected.

**Comment by peterchen-intel** [comment]
@JunxiChhen Can you please also provide the information that how you convert the model? What is your CPU model? Can you reproduce the same on a Core CPU?

**Comment by peterchen-intel** [comment]
https://github.com/openvinotoolkit/openvino.genai/pull/451

**Comment by peterchen-intel** [comment]
@JunxiChhen  PR was merged. Please check if the issue was fixed.

**Comment by yangkunx** [comment]
The value of 1st token lantency or 2nd tokens latency is 0., when test google/flan-t5-xl and baichuan-inc/Baichuan2-7B-Chat.
![image](https://github.com/openvinotoolkit/openvino.genai/assets/122254299/26c28129-d4de-4ec9-afc1-28b3426c6bee)

**Comment by peterchen-intel** [comment]
@yangkunx Can you run following to update transformers(at least 4.40.x)?
pip install -U --upgrade-strategy eager -r requirements.txt
