### ISSUE TITLE
Requesting help to understand how TTFT is calculated. Is there any documentation?

### ISSUE THREAD

**Issue by tsantra** [openvinotoolkit/openvino.genai#381]
### Context

Requesting help to understand how TTFT is calculated

### What needs to be done?

Requesting help to understand how TTFT is calculated

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@ngaloppo @

### Ticket

Requesting help to understand how TTFT is calculated

**Comment by asvin-kumar** [comment]
What's TTFT? Is this about Time to first token in the context of LLMs?
If so, idk the answer. Just wanted to clarify.

**Comment by peterchen-intel** [comment]
@tsantra Time To First Token :  Approximate the cumulation of following 2.  Hope this can answer your question.
[ INFO ] From pretrained time: 6.11s
[ INFO ] [warm-up] First token latency: 2006.40 ms/token

**Comment by peterchen-intel** [comment]
@tsantra Please feel free to ask additional questions by submitting new ticket.
