### ISSUE TITLE
MPT-30B met benchmarking issue

### ISSUE THREAD

**Issue by JunxiChhen** [openvinotoolkit/openvino.genai#388]
![image](https://github.com/openvinotoolkit/openvino.genai/assets/92417411/cc41aaff-b415-4410-8a74-abddcb8a6e94)

Benchmarking cmd: 
```
numactl -C 0-55 -m 0 python benchmark.py     -m /root/.cache/huggingface/hub/mpt-30b-chat-ov/pytorch/dldt/FP16     -p "It is done, and submitted. ..."     -n 2     -bs 1     -d CPU --torch_compile_backend openvino     -ic 128 --num_beams 1 -lc bfloat16_config.json 2>&1 | tee -a ./logs/0.log
```

**Comment by eaidova** [comment]
@JunxiChhen , I reproduced your reported issue, this PR should help https://github.com/openvinotoolkit/openvino.genai/pull/412
For optimal performance, I also recommend reconvert model with the latest changes
