### ISSUE TITLE
chatglm output results are repeating with basic prompts

### ISSUE THREAD

**Issue by avinashbhat09** [openvinotoolkit/openvino.genai#527]
### Context

We see that basic chatglm output generated words are repetitive.

![image](https://github.com/openvinotoolkit/openvino.genai/assets/98947310/f237a08b-a4db-4c6d-80f8-83abb762ad89)

### What needs to be done?

We need to figure out if this is due to weight compression or model issue

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@avinashbhat09

**Comment by avinashbhat09** [comment]
Tried the same OV converted model using chatglm-openvino (https://github.com/OpenVINO-dev-contest/chatglm3.openvino) and it works fine. We dont see any repetitive words.


![image](https://github.com/openvinotoolkit/openvino.genai/assets/98947310/9a8fbc15-3324-421c-9d50-5a77d7c9e33d)

With this we can conclude below:
1. No issue running inference on CPU or GPU

2. Not model issue

3. No quantization issue


This looks more of gen-ai interfacing with the model.

**Comment by avinashbhat09** [comment]
Can we have similar implementation as per chatglm-openvino implementation in the gen-ai supporting chatglm?

**Comment by avinashbhat09** [comment]
Hi, any update on this?

**Comment by avinashbhat09** [comment]
Thanks @Wovchena . Unfortunately, the chat sample does not work for me.
![image](https://github.com/openvinotoolkit/openvino.genai/assets/98947310/c5662de6-3ad9-450d-9ce5-9cfefa32b462)

**Comment by avinashbhat09** [comment]
> Hi. I don't have any update. @peterchen-intel is the correct person to discuss llm_bench related questions with. As for the chatbot kind of implementation, the sample is here https://github.com/openvinotoolkit/openvino.genai/tree/master/samples/python/chat_sample.

@peterchen-intel : Any input from your side?

**Comment by Wovchena** [comment]
Your model is stateless. You need a stateful one. To export such a model, ensure you don't have `--disable-stateful` while running `optimum-cli export openvino`. Alternatively, if you use `python ./llm_bench/python/convert.py`, you need to specify `--stateful` (and not `--disable-stateful`).

**Comment by avinashbhat09** [comment]
Thanks for your input @Wovchena . I converted using this command and it worked.
optimum-cli export openvino --trust-remote-code --model THUDM/chatglm3-6b chatglm3-6b_stateful -**-task question-answering**

![image](https://github.com/openvinotoolkit/openvino.genai/assets/98947310/7bfc004d-0d8f-4551-9eb7-a5ab13e38c19)

So this confirms that we dont have issues with model or quantization. Coming back to original bug- when we use benchmark.py why do we see the answers repeating? Anything can be done to fix that?

**Comment by peterchen-intel** [comment]
It may due to benchmark.py force to output "--infer_count" tokens for performance consistency (with fixed output size instead of stop at end_token). Will add an option to stop_ending_token.

**Comment by peterchen-intel** [comment]
CVS-146307

**Comment by peterchen-intel** [comment]
https://github.com/openvinotoolkit/openvino.genai/pull/606

**Comment by peterchen-intel** [comment]
@avinashbhat09 Can you try HEAD of openvino.genai master branch with option --end_token_stopping?

**Comment by peterchen-intel** [comment]
Link CVS-146307

**Comment by peterchen-intel** [comment]
In some cases, we need to fine tune the prompt to get expected size of output tokens for LLM benchmarking. In order to avoid the fine tune for each model, we set end_token_stopping=false by default to force generating expected size of output tokens. The side effect is that the output looks not good, repeating is one of the cases. It is really a trade-off. The bad outputs doesn't mean accuracy issue, accuracy issue should be tested by accuracy tool, benchmarking tool can't cover it.
