### ISSUE TITLE
[GPU] force exit

### ISSUE THREAD

**Issue by saivivekseeram1** [openvinotoolkit/openvino.genai#551]
### Context

Model is not sufficient to load on the GPU, i want to modify the threshold values in my local system 

### What needs to be done?

if it's possible i want to change the values threshold, top-p, top-k values in my local system. could i get the respective file path, where it could it be modify.

### Resources

![Screenshot 2024-06-25 120109](https://github.com/openvinotoolkit/openvino.genai/assets/92068535/84f6ceb7-e8ce-42b3-a2fe-03c314f0163b)

### Contact points

I had go through the convert and benchmark. i didn't find any arguments related threshold values

**Comment by peterchen-intel** [comment]
@saivivekseeram1 What is your GPU?

**Comment by peterchen-intel** [comment]
Close old issue.
