### ISSUE TITLE
`chat_sample.exe` doesn't work well when using `Llama-2-7b-chat-hf`

### ISSUE THREAD

**Issue by yviansu** [openvinotoolkit/openvino.genai#557]
## Error detail
When running `chat_sample.exe` using `Llama-2-7b-chat-hf`, seems that it always have a built-in question:
![image](https://github.com/openvinotoolkit/openvino.genai/assets/103162767/93e8d38f-e209-46bc-b4f9-08b143780ba6)

## Steps to reproduce
1. Get `Llama-2-7b-chat-hf` models by this command:
```
optimum-cli export openvino --model "meta-llama/Llama-2-7b-chat-hf" --trust-remote-code "meta-llama/Llama-2-7b-chat-hf"
```
2. Build the code by https://github.com/openvinotoolkit/openvino.genai/blob/releases/2024/2/src/docs/BUILD.md#build-instructions-1
3. Run the command:
```
chat_sample.exe C:\models\Llama-2-7b-chat-hf
```

By the way, I also tested `chat_sample.exe` with `TinyLlama-1.1B-Chat-v1.0`, and it works well:
![image](https://github.com/openvinotoolkit/openvino.genai/assets/103162767/74cb3e71-7bf4-43bd-9154-1881ade13af2)

**Comment by pavel-esir** [comment]
This issue is fixed in https://github.com/openvinotoolkit/openvino.genai/pull/549
