### ISSUE TITLE
if there is a sample code to run on NPU?

### ISSUE THREAD

**Issue by Edward-Lin** [openvinotoolkit/openvino.genai#579]
where can I please get the sample code to run LLM on NPU?
Thanks,

**Comment by Wovchena** [comment]
https://github.com/openvinotoolkit/openvino.genai/pull/576

**Comment by Edward-Lin** [comment]
> #576

what do you mean?

**Comment by Edward-Lin** [comment]
I did not know what u mean
![image](https://github.com/openvinotoolkit/openvino.genai/assets/84361410/2d01def6-e09c-4cab-8038-c6b7e02fb728)

**Comment by avitial** [comment]
@Edward-Lin the referenced PR (not merged to master branch yet), seems to contain code changes to support LLM pipeline with static shapes out-of-the-box for NPU plugin. Feel free to try the PR to run the [chat_sample ](https://github.com/openvinotoolkit/openvino.genai/tree/master/samples/cpp/chat_sample), or wait until merge to master branch. Hope this helps.

**Comment by aoke79** [comment]
> @Edward-Lin the referenced PR (not merged to master branch yet), seems to contain code changes to support LLM pipeline with static shapes out-of-the-box for NPU plugin. Feel free to try the PR to run the [chat_sample ](https://github.com/openvinotoolkit/openvino.genai/tree/master/samples/cpp/chat_sample), or wait until merge to master branch. Hope this helps.

Thanks, BTW, what is PR, and how can I get it?

**Comment by aoke79** [comment]
I think I've got it, and have a try.
will update later.
Thanks,

**Comment by aoke79** [comment]
https://github.com/TolyaTalamanov/openvino.genai/tree/at/static-llm-pipeline-out-of-the-box
I've checked out the code, but it only support CPP version, and I need to try to compile it, and not sure if it can run on NPU or not? 
but from the 576, it should not work yet.

![image](https://github.com/openvinotoolkit/openvino.genai/assets/7357656/c9d69c43-d329-467a-a029-8fc6ab04aa0b)

**Comment by TolyaTalamanov** [comment]
Hi! @aoke79,

Once https://github.com/openvinotoolkit/openvino.genai/pull/576/ is merged, you will be able to run `LLMPipeline` on NPU out-of-the-box by using the following code shippet:
```
ov::genai::LLMPipeline pipe(model_path, "NPU");
ov::genai::GenerationConfig config;
config.max_new_tokens = 100; // optional
std::cout << pipe.generate("Why is the Sun yellow?", config) << std::endl;
```

Unfortunately, it doesn't support chat mode  (will be introduced there: https://github.com/openvinotoolkit/openvino.genai/pull/580), so `chat_sample.cpp` cannot be used so far.

**Comment by aoke79** [comment]
Thanks, Tolya, I updated code, and found 576 was merged, but it seems not work for me.
when I changed the "device = 'CPU'  # GPU can be used as well" to "GPU" or "NPU", in greedy_causal_lm.py or beam_search_causal_lm.py, **neither** of them worked. please help check.
Thanks

**Comment by Edward-Lin** [comment]
do you please have the converted tiny llama chat model, which I can try?
I suppose that the model, I converted on my side, is not correct.
thanks,

**Comment by TolyaTalamanov** [comment]
> Thanks, Tolya, I updated code, and found 576 was merged, but it seems not work for me. when I changed the "device = 'CPU' # GPU can be used as well" to "GPU" or "NPU", in greedy_causal_lm.py or beam_search_causal_lm.py, **neither** of them worked. please help check. Thanks

Hi @aoke79, @Edward-Lin  the following snippet should work with regular openvino model (same as for other plugins)
```
ov::genai::LLMPipeline pipe(model_path, "NPU");
ov::genai::GenerationConfig config;
config.max_new_tokens = 100; // optional
std::cout << pipe.generate("Why is the Sun yellow?", config) << std::endl;
```
Additionally, I'd also expect `chat_sample` to work with the latest `master`.

As for `greedy_causal_lm.py` and `beam_search_causal_lm.py` -- they weren't considered during integration, perhaps will be enabled in the future.

**Comment by aoke79** [comment]
Thanks for your advice, I've downloaded the packages from "https://[storage.openvinotoolkit.org](https://storage.openvinotoolkit.org/repositories/openvino_genai/packages/2024.2/windows)/repositories/openvino_genai/packages/2024.2/windows". and build the exe by build_samples_msvc.bat, but when I run any exe file, there is no any ouptut, it's very weird.

there is the compile log:
--------------------------------------------------------------------------------------------------------------------
C:\AIGC\openvino\openvino_genai_windows_2024.2.0.0_x86_64\samples\cpp>build_samples_msvc.bat
Warning: Python is not installed. Please install one of Python 3.8 - 3.12 (64-bit) from https://www.python.org/downloads/
[setupvars.bat] OpenVINO environment initialized
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.39.33523.0
-- The CXX compiler identification is MSVC 19.39.33523.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at thirdparty/gflags/gflags/CMakeLists.txt:73 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
CMake Warning at common/format_reader/CMakeLists.txt:22 (message):
  OpenCV ver.  3.0+ is not found, format_reader will be built without OpenCV
  support

-- Using the multi-header code from C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/thirdparty/nlohmann_json/include/
CMake Warning at benchmark_app/CMakeLists.txt:49 (message):
  OpenCL is disabled or not found, benchmark_app will be built without OpenCL
  support.  Install OpenCL.


CMake Warning at benchmark_app/CMakeLists.txt:104 (message):
  OpenCL CPP header is not found, benchmark_app will be built without OpenCL
  support and you will not be able to use the '-use_device_mem' option.
  Please, install '<apt | yum> install opencl-headers' to enable the option


CMake Warning at benchmark_app/CMakeLists.txt:112 (message):
  OpenCV ver.  3.0+ is not found, benchmark_app will be built without OpenCV
  support.  Set OpenCV_DIR


-- Configuring done (7.3s)
-- Generating done (0.2s)
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_DISABLE_FIND_PACKAGE_PkgConfig


-- Build files have been written to: C:/Users/Administrator/Documents/Intel/OpenVINO/openvino_cpp_samples_build

###############|| Build OpenVINO Runtime samples using MS Visual Studio (MSBuild.exe) ||###############

cmake --build "C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build" --config Release --parallel
MSBuild version 17.9.8+b34f75857 for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/commo
  n/format_reader/CMakeLists.txt
  MnistUbyte.cpp
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/third
  party/gflags/gflags/CMakeLists.txt
  gflags.cc
  bmp.cpp
  format_reader.cpp
  gflags_reporting.cc
  npy.cpp
  gflags_completions.cc
  opencv_wrapper.cpp
  yuv_nv12.cpp
  Generating Code...
  windows_port.cc
  Generating Code...
  format_reader.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_bu
  ild\intel64\Release\format_reader.lib
  gflags_nothreads_static.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_
  samples_build\intel64\Release\gflags_nothreads_static.lib
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/commo
  n/utils/CMakeLists.txt
  args_helper.cpp
  latency_metrics.cpp
  slog.cpp
  Generating Code...
  ie_samples_utils.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples
  _build\intel64\Release\ie_samples_utils.lib
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/class
  ification_sample_async/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/hello
  _classification/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/hello
  _nv12_input_classification/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/hello
  _reshape_ssd/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/bench
  mark/sync_benchmark/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/bench
  mark/throughput_benchmark/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/model
  _creation_sample/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/hello
  _query_device/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/bench
  mark_app/CMakeLists.txt
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  inputs_filling.cpp
  sync_benchmark.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_b
  uild\intel64\Release\sync_benchmark.exe
  hello_query_device.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_sampl
  es_build\intel64\Release\hello_query_device.exe
  hello_classification.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_sam
  ples_build\intel64\Release\hello_classification.exe
  classification_sample_async.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_
  cpp_samples_build\intel64\Release\classification_sample_async.exe
  throughput_benchmark.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_sam
  ples_build\intel64\Release\throughput_benchmark.exe
  main.cpp
  hello_nv12_input_classification.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openv
  ino_cpp_samples_build\intel64\Release\hello_nv12_input_classification.exe
  hello_reshape_ssd.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_sample
  s_build\intel64\Release\hello_reshape_ssd.exe
  model_creation_sample.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_sa
  mples_build\intel64\Release\model_creation_sample.exe
  remote_tensors_filling.cpp
  statistics_report.cpp
  utils.cpp
  Generating Code...
  benchmark_app.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_bu
  ild\intel64\Release\benchmark_app.exe
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/bench
  mark/sync_benchmark/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/beam_
  search_causal_lm/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/chat_
  sample/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/greed
  y_causal_lm/CMakeLists.txt
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/multi
  nomial_causal_lm/CMakeLists.txt
  greedy_causal_lm.cpp
  multinomial_causal_lm.cpp
  beam_search_causal_lm.cpp
  chat_sample.cpp
C:\AIGC\openvino\openvino_genai_windows_2024.2.0.0_x86_64\samples\cpp\multinomial_causal_lm\multin
omial_causal_lm.cpp(20,20): warning C4305: '=': truncation from 'double' to 'float' [C:\Users\Admi
nistrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\multinomial_causal_lm\multinomial_ca
usal_lm.vcxproj]
  chat_sample.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_buil
  d\intel64\Release\chat_sample.exe
  greedy_causal_lm.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples
  _build\intel64\Release\greedy_causal_lm.exe
  beam_search_causal_lm.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_sa
  mples_build\intel64\Release\beam_search_causal_lm.exe
  multinomial_causal_lm.vcxproj -> C:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_sa
  mples_build\intel64\Release\multinomial_causal_lm.exe
  Building Custom Rule C:/AIGC/openvino/openvino_genai_windows_2024.2.0.0_x86_64/samples/cpp/CMake
  Lists.txt
Done.
--------------------------------------------------------------------------------------------------------------------
run chat_sample.exe, there is no any output.
C:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\FP16
(env_ov_genai) c:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\intel64\Release>chat_sample.exe C:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\compressed_weights\OV_FP16-4BIT_DEFAULT

(env_ov_genai) c:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\intel64\Release>chat_sample.exe "C:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\compressed_weights\OV_FP16-4BIT_DEFAULT"

(env_ov_genai) c:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\intel64\Release>chat_sample.exe "C:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\compressed_weights\OV_FP16-4BIT_DEFAULT"

(env_ov_genai) c:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\intel64\Release>
--------------------------------------------------------------------------------------------------------------------
when I disable other code, only write below code, it runs ok.
int main(int argc, char* argv[])
{
    std::cout << "\n-----step 0-----\n";
    if (2 != argc) {
        std::cout << std::string{"Usage: "} << argv[0] << " <MODEL_DIR>";
        return 0;
    }
}
--------------------------------------------------------------------------------------------------------------------
it seemed that when I call LLMPipeline, there is no any output, very weird. 
    ov::genai::LLMPipeline pipe(model_path, "NPU");
--------------------------------------------------------------------------------------------------------------------

might you please give me the full compile/run code or pipeline, it bothers me for a while?
Thanks very much

**Comment by aoke79** [comment]
I've run it on GPU OK through the GenAI.
Might you please share the converted models on NPU, like TinyLlama-1.1B-Chat-v1.0. I run the same code with the same model, failed to run on NPU, but ok on GPU.
Thanks a lot,

**Comment by aoke79** [comment]
(env_ov_genai) c:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\intel64\Release>chat_sample.exe C:\AIGC\openvino\Optimum\tiny-int4-sym-npu

-----main-----
question:
why the Sun is yellow?
Check 'num_inputs == 4 || num_inputs == 3' failed at src/cpp/src/llm_pipeline.cpp:207:
Model should have 3 or 4 inputs: either (input_ids, attention_mask, beam_idx) or (input_ids, attention_mask, position_ids, beam_idx) but you have '47' inputs


(env_ov_genai) c:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\intel64\Release>chat_sample.exe C:\AIGC\openvino\Optimum\tiny-int4-sym-npu

-----main-----
question:
why the Sun is yellow?
Check 'num_inputs == 4 || num_inputs == 3' failed at src/cpp/src/llm_pipeline.cpp:207:
Model should have 3 or 4 inputs: either (input_ids, attention_mask, beam_idx) or (input_ids, attention_mask, position_ids, beam_idx) but you have '47' inputs

do you please know where I can download a NPU compatible model?
Thanks,

**Comment by TolyaTalamanov** [comment]
> (env_ov_genai) c:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\intel64\Release>chat_sample.exe C:\AIGC\openvino\Optimum\tiny-int4-sym-npu
> 
> -----main----- question: why the Sun is yellow? Check 'num_inputs == 4 || num_inputs == 3' failed at src/cpp/src/llm_pipeline.cpp:207: Model should have 3 or 4 inputs: either (input_ids, attention_mask, beam_idx) or (input_ids, attention_mask, position_ids, beam_idx) but you have '47' inputs
> 
> (env_ov_genai) c:\Users\Administrator\Documents\Intel\OpenVINO\openvino_cpp_samples_build\intel64\Release>chat_sample.exe C:\AIGC\openvino\Optimum\tiny-int4-sym-npu
> 
> -----main----- question: why the Sun is yellow? Check 'num_inputs == 4 || num_inputs == 3' failed at src/cpp/src/llm_pipeline.cpp:207: Model should have 3 or 4 inputs: either (input_ids, attention_mask, beam_idx) or (input_ids, attention_mask, position_ids, beam_idx) but you have '47' inputs
> 
> do you please know where I can download a NPU compatible model? Thanks,

@aoke79 Hi! You don't need NPU compatible models, you should be able to use the same models as for CPU / GPU devices.
Please make sure, your GenAI version contains the following change: https://github.com/openvinotoolkit/openvino.genai/pull/576

**Comment by aoke79** [comment]
thanks for response. but I don't think so, here is my git log, I suppose it support 579:
commit 0c2b68e469008fcc33f53da884d3e3b87df8dad0 (HEAD -> master, origin/master, origin/HEAD)
Author: Zlobin Vladimir <vladimir.zlobin@intel.com>
Date:   Fri Jul 19 13:27:33 2024 +0400

    rm .github/ISSUE_TEMPLATE (#646)

    GenAI issues found by the commpunity tend to be crated using that
    template which isn't correct because they usually expect us to address
    them.

commit fcc309ef00ef0020a8a93bf1f7e08664eb6d2bcb (origin/gh-readonly-queue/master/pr-643-7f5e8d293468754e148c274533b7c3e790b78198)
Author: Pavel Esir <pavel.esir@gmail.com>
Date:   Thu Jul 18 11:30:31 2024 +0200

    add testing chat_templates for models from continuous batching (#643)

    and added missing chat_templates for models from
    https://github.com/ilya-lavrenov/openvino.genai/blob/ct-beam-search/text_generation/causal_lm/cpp/continuous_batching/python/tests/models/real_models

    Missing models were:
    `mistralai/Mistral-7B-Instruct-v0.1`
    `microsoft/Phi-3-mini-4k-instruct, microsoft/Phi-3-mini-128k-instruct` -
    same templates
    `THUDM/chatglm3-6b`

    Mistral will be added separately. Also increased priority to enable
    apply_chat_template firstly for CB models from the list above.

**Comment by aoke79** [comment]
I downloaded a packaged from genai official website, and it can compile the cpp code, but I don't know how to compile genai.cpp code. can you please tell me how to compile the genai cpp code? is there any guide?
"openvino_genai_windows_2024.2.0.0_x86_64.zip"

**Comment by TolyaTalamanov** [comment]
> I downloaded a packaged from genai official website, and it can compile the cpp code, but I don't know how to compile genai.cpp code. can you please tell me how to compile the genai cpp code? is there any guide? "openvino_genai_windows_2024.2.0.0_x86_64.zip"

@Wovchena FYI

**Comment by TolyaTalamanov** [comment]
> thanks for response. but I don't think so, here is my git log, I suppose it support 579: commit [0c2b68e](https://github.com/openvinotoolkit/openvino.genai/commit/0c2b68e469008fcc33f53da884d3e3b87df8dad0) (HEAD -> master, origin/master, origin/HEAD) Author: Zlobin Vladimir [vladimir.zlobin@intel.com](mailto:vladimir.zlobin@intel.com) Date: Fri Jul 19 13:27:33 2024 +0400
> 
> ```
> rm .github/ISSUE_TEMPLATE (#646)
> 
> GenAI issues found by the commpunity tend to be crated using that
> template which isn't correct because they usually expect us to address
> them.
> ```
> 
> commit [fcc309e](https://github.com/openvinotoolkit/openvino.genai/commit/fcc309ef00ef0020a8a93bf1f7e08664eb6d2bcb) (origin/gh-readonly-queue/master/pr-643-7f5e8d293468754e148c274533b7c3e790b78198) Author: Pavel Esir [pavel.esir@gmail.com](mailto:pavel.esir@gmail.com) Date: Thu Jul 18 11:30:31 2024 +0200
> 
> ```
> add testing chat_templates for models from continuous batching (#643)
> 
> and added missing chat_templates for models from
> https://github.com/ilya-lavrenov/openvino.genai/blob/ct-beam-search/text_generation/causal_lm/cpp/continuous_batching/python/tests/models/real_models
> 
> Missing models were:
> `mistralai/Mistral-7B-Instruct-v0.1`
> `microsoft/Phi-3-mini-4k-instruct, microsoft/Phi-3-mini-128k-instruct` -
> same templates
> `THUDM/chatglm3-6b`
> 
> Mistral will be added separately. Also increased priority to enable
> apply_chat_template firstly for CB models from the list above.
> ```

@aoke79 Could you clarify what model are you using and GenAI code snippet, please?
 Would be great if you could provide `optimum-cli` command line so I could generate the model on my side

**Comment by aoke79** [comment]
Dear,
maybe there is mis-understanding here.
First of all, I tried to use the code you've provided to me, like below. I believed it's a C++ code, but I don't know how to compile it. 
can you please show me how to compile it?
------------------------------------
ov::genai::LLMPipeline pipe(model_path, "NPU");
ov::genai::GenerationConfig config;
config.max_new_tokens = 100; // optional
std::cout << pipe.generate("Why is the Sun yellow?", config) << std::endl;
------------------------------------

Secondly, I downloaded a genai package, which have the "build_samples_msvc.bat" file to compile the C++ code, I've got the exe files through it. but it still failed to load model on NPU. so I guess that:
1. maybe the code is not the latest, so I've asked for a compiling way to compile the sample code through sample code.
2. maybe, I need some specific converted model for NPU, so I asked for the model if you can provided one.

so might you please share some completely steps, which I can follow to do the test, not just some suggestions?

Thanks very much

**Comment by aoke79** [comment]
https://hf-mirror.com/TinyLlama/TinyLlama-1.1B-Chat-v1.0

**Comment by avitial** [comment]
Hi @aoke79 if it helps you can take a look at the following PR for guidance with LLMs on NPU: https://github.com/openvinotoolkit/openvino/pull/25841. Here is the [Run LLMs with OpenVINO GenAI Flavor on NPU](https://github.com/openvinotoolkit/openvino/blob/master/docs/articles_en/learn-openvino/llm_inference_guide/genai-guide-npu.rst) guide. Hope this helps.

**Comment by TolyaTalamanov** [comment]
@aoke79 There is also step-by-step guide to run `benchmark_genai`.
https://github.com/openvinotoolkit/openvino.genai/issues/834
