### ISSUE TITLE
where to download a converted model for Tiny Llama Chat for NPU? (int4, or int8)

### ISSUE THREAD

**Issue by Edward-Lin** [openvinotoolkit/openvino.genai#665]
Dears,
I'd like to try tiny llama chat on NPU, but it always showed the error about static shape.
might you please show me where I can download a quanted model for it, both Int4 and int8?
or tell me the ways to convert it.
thanks a lot,

**Comment by TolyaTalamanov** [comment]
Hi @Edward-Lin, 

You can find the documentation for running Tiny LLaMA on NPU, including how to convert and quantize model to int4, here: https://openvino-doc.iotg.sclab.intel.com/genai-npu-preview-master/learn-openvino/llm_inference_guide/genai-guide-npu.html

**Comment by TolyaTalamanov** [comment]
@Edward-Lin have you managed to convert the model by using the guide above?

**Comment by Edward-Lin** [comment]
![image](https://github.com/user-attachments/assets/ecc13aa9-b8cf-4bf2-94c0-ef17f66ef765)

**Comment by TolyaTalamanov** [comment]
@Edward-Lin sorry, wrong link, changed in-place
