### ISSUE TITLE
How to compile samples/cpp code?

### ISSUE THREAD

**Issue by aoke79** [openvinotoolkit/openvino.genai#682]
Dear,
might you please give a script or a "bat" file to compile the genai cpp code, include "src", "samples\cpp"?
thanks,

**Comment by Wovchena** [comment]
There's no bat to build the whole project. Follow the instruction: https://github.com/openvinotoolkit/openvino.genai/blob/master/src/docs/BUILD.md

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
