### ISSUE TITLE
 convert.py do NOT support Meta-Llama-3.1-8B-Instruct

### ISSUE THREAD

**Issue by openvino-book** [openvinotoolkit/openvino.genai#709]
Run [convert.py](https://github.com/openvinotoolkit/openvino.genai/blob/master/llm_bench/python/convert.py) on Meta-Llama-3.1-8B-Instruct model, Error occur as below:
> ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}

![1722391465029](https://github.com/user-attachments/assets/85787f84-7dbd-4665-b26e-226f2403ab99)

**Comment by eaidova** [comment]
@openvino-book according to this issue on hf hub, you need to upgrade transformers for loading llama3.1 https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/15

**Comment by openvino-book** [comment]
> @openvino-book according to this issue on hf hub, you need to upgrade transformers for loading llama3.1 https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/15

Thank you @eaidova , it works!
> pip install --upgrade transformers
the worked version of transformers is 4.43.3

![1722734952888](https://github.com/user-attachments/assets/aaadb413-ab14-4e56-bd84-c4e87e27b824)

**Comment by openvino-book** [comment]
Hi, @eaidova , after update the transformers, the convert.py works well. 

However, the benchmark.py raise an error  as below when running the converted Llama3.1 IR model.

![1722736391336](https://github.com/user-attachments/assets/e7822026-a12c-4e84-b19f-937a333c1a7c)

**Comment by openvino-book** [comment]
running on the CPU has the same error
![1722736622228](https://github.com/user-attachments/assets/cd2d2111-d6c7-483c-9e1d-37eaeeea43a9)

**Comment by openvino-book** [comment]
Hi, @eaidova  very interesting, there are not openvino_tokenizer.xml & openvino_detokenizer.xml in the converted model D:\openvino.genai\llm_bench\python\llama31_ov\pytorch\dldt\FP16
![1722739251500](https://github.com/user-attachments/assets/9c5346f8-dcd8-4dd8-a4f8-fe8edc968379)

**Comment by peterchen-intel** [comment]
> Hi, @eaidova very interesting, there are not openvino_tokenizer.xml & openvino_detokenizer.xml in the converted model D:\openvino.genai\llm_bench\python\llama31_ov\pytorch\dldt\FP16

@openvino-book If this issue can still be reproduced with latest openvino.genai? https://github.com/openvinotoolkit/openvino.genai
