### ISSUE TITLE
Filed to run chat_sample on NPU

### ISSUE THREAD

**Issue by liuxt670** [openvinotoolkit/openvino.genai#776]
Hi, we have successfully ran your chat_sample using our 1.8b llm on NPU based on version nightly-20240726, but it doesn't work since we updated openvino and openvino.genai to version nightly-20240812. Is there any change? The CPU of our device is Intel Core Ultra 5.
Can you give us any suggestions?
Thanks a lot!

**Comment by dmatveev** [comment]
@liuxt670 thanks for report, please let us know what is the OS / driver version you use.

**Comment by liuxt670** [comment]
@dmatveev Thanks for the reply, our OS is Windows 11 and NPU driver version is 32.0.100.2540

**Comment by TolyaTalamanov** [comment]
> @dmatveev Thanks for the reply, our OS is Windows 11 and NPU driver version is 32.0.100.2540

@liuxt670 Could you also elaborate on `nightly-20240726` version, where did you take it from?

**Comment by liuxt670** [comment]
@TolyaTalamanov 
Openvino: https://storage.openvinotoolkit.org/repositories/openvino/packages/nightly/2024.4.0-16130-a3ed68a590b/
Openvino.genai: https://storage.openvinotoolkit.org/repositories/openvino_genai/packages/nightly/2024.4.0.0.dev20240726/

**Comment by szeyu** [comment]
> @TolyaTalamanov Openvino: https://storage.openvinotoolkit.org/repositories/openvino/packages/nightly/2024.4.0-16130-a3ed68a590b/ Openvino.genai: https://storage.openvinotoolkit.org/repositories/openvino_genai/packages/nightly/2024.4.0.0.dev20240726/

Hi wanna ask, how do you resolve the dependencies using these version?

```
pip install --pre "openvino<=2024.4.0.0.dev20240726" "openvino-genai<=2024.4.0.0.dev20240726" "openvino-tokenizers<=2024.3.0.0.dev20240726" --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
```

After I install and view from `pip list`

the version that I got is 
```
openvino                  2024.3.0
openvino-genai            2024.4.0.0.dev20240726
openvino-telemetry        2024.1.0
openvino-tokenizers       2024.3.0.0.dev20240711
```

**Comment by TolyaTalamanov** [comment]
> > @TolyaTalamanov Openvino: https://storage.openvinotoolkit.org/repositories/openvino/packages/nightly/2024.4.0-16130-a3ed68a590b/ Openvino.genai: https://storage.openvinotoolkit.org/repositories/openvino_genai/packages/nightly/2024.4.0.0.dev20240726/
> 
> Hi wanna ask, how do you resolve the dependencies using these version?
> 
> ```
> pip install --pre "openvino<=2024.4.0.0.dev20240726" "openvino-genai<=2024.4.0.0.dev20240726" "openvino-tokenizers<=2024.3.0.0.dev20240726" --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
> ```
> 
> After I install and view from `pip list`, it seems like `openvino-tokenizers` and `openvino` version are dependant of each other. so I wanna ask what is your version of `openvino-tokenizers` and `openvino`? the version that I got is
> 
> ```
> openvino                  2024.3.0
> openvino-genai            2024.4.0.0.dev20240726
> openvino-telemetry        2024.1.0
> openvino-tokenizers       2024.3.0.0.dev20240711
> ```

@szeyu Could you check https://github.com/openvinotoolkit/openvino.genai/issues/834 and https://docs.openvino.ai/2024/learn-openvino/llm_inference_guide/genai-guide-npu.html, please?

Perhaps you need to start with clear python environment (`python -m venv ov-env`)

**Comment by TolyaTalamanov** [comment]
@liuxt670 Can you double check with the latest available versions, please?
```
python -m venv ov-env
ov-env\Scripts\activate
pip install --pre openvino openvino-tokenizers openvino-genai --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
```

pip list:
```
openvino 2024.5.0.dev20240909
openvino-genai 2024.5.0.0.dev20240909
openvino-telemetry 2024.1.0
openvino-tokenizers 2024.5.0.0.dev20240909
```

The following works fine with `Tiny-Llama` converted like this: https://docs.openvino.ai/2024/learn-openvino/llm_inference_guide/genai-guide-npu.html
```
cd openvino.genai\samples\python\chat_sample
python chat_sample.py <path-to-model>
```

**Comment by szeyu** [comment]
> @liuxt670 Can you double check with the latest available versions, please?
> 
> ```
> python -m venv ov-env
> ov-env\Scripts\activate
> pip install --pre openvino openvino-tokenizers openvino-genai --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
> ```
> 
> pip list:
> 
> ```
> openvino 2024.5.0.dev20240909
> openvino-genai 2024.5.0.0.dev20240909
> openvino-telemetry 2024.1.0
> openvino-tokenizers 2024.5.0.0.dev20240909
> ```
> 
> The following works fine with `Tiny-Llama` converted like this: https://docs.openvino.ai/2024/learn-openvino/llm_inference_guide/genai-guide-npu.html
> 
> ```
> cd openvino.genai\samples\python\chat_sample
> python chat_sample.py <path-to-model>
> ```

Hi I have followed the exact step that you have provided until before the `chat_sample.py`. I think that yours is working maybe you forgot to change the 

`device="NPU"` in the `chat_sample.py`?
since this thread is about NPU. Of course I have succeeded in running in *CPU* as well but failed on *NPU*.

This is the error output that I have gotten when running in *NPU*

```
Traceback (most recent call last):
  File "C:\Users\hpintel\Documents\openvino.genai\samples\python\chat_sample\chat_sample.py", line 39, in <module>
    main()
  File "C:\Users\hpintel\Documents\openvino.genai\samples\python\chat_sample\chat_sample.py", line 33, in main
    pipe.generate(prompt, config, streamer)
RuntimeError: Exception from src\inference\src\cpp\infer_request.cpp:223:
Check 'byte_size == 0 || data != nullptr' failed at src\inference\src\dev\make_tensor.cpp:208:
Failed to allocate memory
```

- My NPU driver version is `32.0.100.2688`
- My pip list:
```
openvino                  2024.5.0.dev20240910
openvino-genai            2024.5.0.0.dev20240910
openvino-telemetry        2024.1.0
openvino-tokenizers       2024.5.0.0.dev20240910
```

**Comment by szeyu** [comment]
Also from what I have found from the [NPU_Win_Release_Notes_v2688.pdf](https://downloadmirror.intel.com/829143/NPU_Win_Release_Notes_v2688.pdf), it is stated that the supported version of OpenVINO framework is 2024.3

![image](https://github.com/user-attachments/assets/a764b640-b402-49a1-a166-afda087e7655)

I think this might be related to this issue as well

**Comment by szeyu** [comment]
![image](https://github.com/user-attachments/assets/08c39727-39dc-4215-9e0d-54669d752dc9)

Alright! Now then it works. Seems like the documentation of Intel driver need some changes, else it will be confusing. The documentation need to state the driver version that work for Openvino running on NPU.

Anyways thanks for your help. It works on my side with

* NPU Driver : **Intel® NPU Driver - Windows* 32.0.100.2714**

* Pip lists : 
  ```
  openvino                  2024.5.0.dev20240911
  openvino-genai            2024.5.0.0.dev20240911
  openvino-telemetry        2024.1.0
  openvino-tokenizers       2024.5.0.0.dev20240911
  ```

* LLM Model : 
  `optimum-cli export openvino -m microsoft/Phi-3-mini-4k-instruct --weight-format int4 --sym --group-size 128 --ratio 1.0 Phi-3-mini-4k-instruct-sym-int4-ov`

* Python code :
```
import openvino_genai as ov_genai
model_path = "Phi-3-mini-4k-instruct-sym-int4-ov"
pipe = ov_genai.LLMPipeline(model_path, "NPU")
print("testing")
print(pipe.generate("The Sun is yellow because", max_new_tokens=100))
```

I think there is no issue for now. @TolyaTalamanov you can close the issue for now. Thanks for you help.
