### ISSUE TITLE
failed to run sample/benchmark_genai.py on NPU for tiny-llama-chat-v1.0

### ISSUE THREAD

**Issue by aoke79** [openvinotoolkit/openvino.genai#821]
I've run the benchmark_genai.py for CPU, GPU, NPU on MTL U9, here is the logs:
(env_ov_genai) c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai>python benchmark_genai.py -m c:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\OV_FP16-4BIT_DEFAULT -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d CPU
Load time: 1517.00 ms
Generate time: 89.19 ± 0.00 ms
Tokenization time: nan ± nan ms
Detokenization time: nan ± nan ms
TTFT: 89.18 ± 0.00 ms
TPOT: 89.18 ± 0.00 ms
Throughput : 11.21 ± 0.00 tokens/s

(env_ov_genai) c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai>python benchmark_genai.py -m c:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\OV_FP16-4BIT_DEFAULT -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d GPU
Load time: 4647.00 ms
Generate time: 29.11 ± 0.00 ms
Tokenization time: nan ± nan ms
Detokenization time: nan ± nan ms
TTFT: 29.04 ± 0.00 ms
TPOT: 29.04 ± 0.00 ms
Throughput : 34.44 ± 0.00 tokens/s

(env_ov_genai) c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai>python benchmark_genai.py -m c:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\OV_FP16-4BIT_DEFAULT -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d NPU
Traceback (most recent call last):
  File "c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai\benchmark_genai.py", line 49, in <module>
    main()
  File "c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai\benchmark_genai.py", line 32, in main
    pipe.generate(prompt, config)
RuntimeError: Exception from C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino.genai\src\cpp\src\llm_pipeline_static.cpp:206:
**_Currently only batch size=1 is supported_**

Thanks a lot,

**Comment by TolyaTalamanov** [comment]
Hi @aoke79,

Indeed, using a batch size different from 1 isn't supported on NPU at the moment. However, from the command line you've shared, I don't see any indications that the batch size is involved.

Could you please share the model you're working with or provide the recipe you used to generate it?

Thanks!

**Comment by aoke79** [comment]
Thanks a lot for your quick response. 
I just used the sample code provided from this code base, 
here is the code, https://github.com/openvinotoolkit/openvino.genai/blob/master/samples/python/chat_sample/chat_sample.py.
I just modified the code from "CPU" to "NPU".

    device = 'NPU'  # GPU can be used as well
    pipe = openvino_genai.LLMPipeline(args.model_dir, device)

    config = openvino_genai.GenerationConfig()
    config.max_new_tokens = 100

so I assume that it might due to the converted model. 
Have you ever tried on your side?
Thanks a lot,

**Comment by aoke79** [comment]
Why did you close it? it does not be resolved?

**Comment by peterchen-intel** [comment]
@aoke79 Can you just paste the model link here? so it works for chat_sample.py, but not for benchmark_genai.py?

**Comment by peterchen-intel** [comment]
Close this one since @aoke79  has already duplicated a new one https://github.com/openvinotoolkit/openvino.genai/issues/834
