### ISSUE TITLE
Need perf_metrics support for NPU

### ISSUE THREAD

**Issue by weberwcwei** [openvinotoolkit/openvino.genai#833]
Current performance metrics only support for intel CPU and GPU.

I encountered a runtime error while attempting to run the following script,
```
import openvino_genai as ov_genai

pipe = ov_genai.LLMPipeline("TinyLlama_v1.0_int8", "NPU")
config = ov_genai.GenerationConfig()
config.max_new_tokens = 20
prompt = ["The Sky is blue because"]
res = pipe.generate(prompt, config)
```

However, the following error message was returned:
```
RuntimeError                              Traceback (most recent call last)
Cell In[32], [line 1](vscode-notebook-cell:?execution_count=32&line=1)
----> [1](vscode-notebook-cell:?execution_count=32&line=1) res = pipe.generate(prompt, config)

RuntimeError: Exception from C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino.genai\src\cpp\src\llm_pipeline_static.cpp:223:
Currently only batch size=1 is supported
```

It appears that the current performance metrics only support Intel CPUs and GPUs. Is there a workaround or update for supporting the NPU, or is this a known issue being worked on?

**Comment by aoke79** [comment]
I have the same question, however, someone closed my issue, it's weird, https://github.com/openvinotoolkit/openvino.genai/issues/821.

**Comment by TolyaTalamanov** [comment]
Hi Folks! @weberwcwei, @aoke79 

Could you try to use `prompt = "The Sky is blue because"`?

Also, this problem shouldn't exist for the latest (`nightly`) pip version.
```
pip install --pre openvino openvino-tokenizers openvino-genai --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
```

**Comment by weberwcwei** [comment]
Hi @TolyaTalamanov, 
The string prompt will only return a string output rather than a perf_metric object. 
I have tried the latest update, and the issue with len(prompt) has been resolved. Thank you for the update!

**Comment by TolyaTalamanov** [comment]
Hi @weberwcwei with latest update, did you get `perf_metric` object?

**Comment by weberwcwei** [comment]
Hi @TolyaTalamanov, yes, I got the performance metric by running the script mentioned here (https://github.com/openvinotoolkit/openvino.genai/issues/833#issue-2508583944).

**Comment by TolyaTalamanov** [comment]
Good to know, thank you! Closing then
