### ISSUE TITLE
NPU Turbo Mode support

### ISSUE THREAD

**Issue by addisokw** [openvinotoolkit/openvino.genai#849]
Is there currently a way to pass the NPU Turbo mode parameters to LLMPipeline()?

**Comment by Wan-Intel** [comment]
You may use one of the following codes to set the npu_turbo mode:

`core.set_property("NPU", ov::intel_npu::turbo(true));
`
or

`core.compile_model(ov_model, "NPU", {ov::intel_npu::turbo(true)});
`

For more information, please refer to [npu_turbo](https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.html#supported-features-and-properties:~:text=%2C%20config)%3B-,npu_turbo,-The%20turbo%20mode) in [Supported Features and properties](https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.html#supported-features-and-properties) in [NPU Device](https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.html#npu-device).

**Comment by avitial** [comment]
@addisokw based on [this guide](https://docs.openvino.ai/2024/learn-openvino/llm_inference_guide/genai-guide-npu.html) and as per info provided by Wan, I believe the proper way to set `npu_turbo` mode with `LLMPipeline()` is shown below. Please have a try on your side and see if it works, hope this helps.

```
plugin_config = { "NPU_TURBO": True }
pipeline_config = { "PREFILL_CONFIG": plugin_config, "GENERATE_CONFIG": plugin_config }
pipe = ov_genai.LLMPipeline(model_path, "NPU", pipeline_config)
```

**Comment by addisokw** [comment]
This appears to have worked. Thanks!
