### ISSUE TITLE
Need more documentation about the usage of ov_genai.LLMPipeline

### ISSUE THREAD

**Issue by szeyu** [openvinotoolkit/openvino.genai#855]
I know that the code is written in C++. Hence I am not able to ctrl click to the source code of LLMPipeline in ov_genai. 

for example:
when I write
`pipe = ov_genai.LLMPipeline(model_path, "NPU")`
I don't know what function it has when I type `pipe.___`

This is very frustrating because I won't be able to fully know how it works and might have written a risky and vulnerable code for it. 

Hence I would appreciate if you guys could provide at least more than what is written in [https://github.com/openvinotoolkit/openvino.genai/blob/master/src/README.md](https://github.com/openvinotoolkit/openvino.genai/blob/master/src/README.md)

**Comment by Wovchena** [comment]
What does `.___` do? `python -c "import numpy; numpy.empty(0).___"` fails with
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute '___'
```

You can still use `dir(pipe)` to see all the member functions. You can also find docstrings in https://github.com/openvinotoolkit/openvino.genai/blob/master/src/python/py_generate_pipeline.cpp. The documentation wasn't regenerated yet with these docstrings. You should expect it to appear at https://docs.openvino.ai/2024/api/genai_api/_autosummary/openvino_genai.html later.
