### ISSUE TITLE
how to understand the benchmark_genai's results matrix?

### ISSUE THREAD

**Issue by aoke79** [openvinotoolkit/openvino.genai#875]
how to understand the report matrix, like TTFT, TPOT, Throughput, etc.
which one is the first token latency, and second token average time?

Load time: 18507.00 ms
Generate time: 21.88 ± 1.20 ms
Tokenization time: 0.28 ± 0.02 ms
Detokenization time: 0.94 ± 0.73 ms
TTFT: 20.88 ± 0.47 ms
TPOT: 20.88 ± 0.47 ms
Throughput : 47.89 ± 1.07 tokens/s

Thanks a lot,

**Comment by Wovchena** [comment]
You can find the description at https://github.com/openvinotoolkit/openvino.genai/blob/6003234f6bbb03cb3f5a3e66f4a4f5ce00cdeb18/src/cpp/include/openvino/genai/perf_metrics.hpp#L55
