### ISSUE TITLE
[GPU] Context was not initialized for 0 device

### ISSUE THREAD

**Issue by lonngxiang** [openvinotoolkit/openvino.genai#920]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], [line 2](vscode-notebook-cell:?execution_count=1&line=2)
      [1](vscode-notebook-cell:?execution_count=1&line=1) import openvino_genai as ov_genai
----> [2](vscode-notebook-cell:?execution_count=1&line=2) pipe = ov_genai.LLMPipeline("/ai/qwen2.5-1.5b-ov", "GPU")

RuntimeError: Exception from src/inference/src/cpp/core.cpp:121:
Exception from src/inference/src/dev/plugin.cpp:58:
Check 'contexts.count(device_id)' failed at src/plugins/intel_gpu/src/plugin/plugin.cpp:209:
[GPU] Context was not initialized for 0 device
![image](https://github.com/user-attachments/assets/7ea8e190-eb1b-4a39-896b-923e72906364)

**Comment by Wovchena** [comment]
Is it integrated or discrete GPU? Please, verify GPU driver is installed.

**Comment by lonngxiang** [comment]
> Is it integrated or discrete GPU? Please, verify GPU driver is installed.
installed
![image](https://github.com/user-attachments/assets/c610c93f-f687-4ea6-8cba-f636e6615a53)

**Comment by lonngxiang** [comment]
use CPU work

**Comment by lonngxiang** [comment]
> NVIDIA inference requires compiling https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/nvidia_plugin which wasn't tested with genai.
> 
> Alternatively you can run inference on intel GPU. See https://docs.openvino.ai/2024/get-started/configurations/configurations-intel-gpu.html

tks，How to check the real-time consumption of GPU after installation

**Comment by Wovchena** [comment]
There's intel_gpu_top for intel GPU.

**Comment by Wan-Intel** [comment]
Hi @lonngxiang 
Just wanted to follow up and see if your issue has been resolved by @Wovchena suggestions.

**Comment by andrei-kochin** [comment]
Closing for now. @lonngxiang please feel free to re-open if it is still actual
